# -*- coding: utf-8 -*-
/*"""Fine-tuning GPT - Therapist Chatbot

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x2vAzTv65HAizmQUvK1rfekCTtBnqNYb

**Libraries**
"""

import json
import yaml
from google.colab import files

"""**Connection with Google Drive**"""

from google.colab import drive
drive.mount('/content/gdrive')

# Open the file depression.yml
with open('/content/gdrive/MyDrive/TherapistBot/depression.yml', 'r') as file:
     data = yaml.safe_load(file)

data

"""**Preparation of the dataset in the required format**"""

convs = data['conversations']
output = []

# Splits the first line as the prompt, and joins the rest of the lines as the completion
for conv in convs:
  complet = ''
  for i, dialog in enumerate(conv):
    if i == 0:
      prompt = dialog
      prompt = prompt.replace("\xa0", " ")
    else:
      complet += " " + dialog
      complet = complet.replace("\xa0", " ")
  complet = complet.strip()
  line = {'prompt': prompt, 'completion': complet}
  output.append(line)
    
print(output)

"""**Download the data in jsonl format**"""

with open('depression.jsonl', 'w') as outfile:
        for i in output:
            json.dump(i, outfile)
            outfile.write('\n')


files.download('depression.jsonl')

# Installation of openai
!pip install openai==0.26.1

"""**Prepare the finetunes data**"""

!openai tools fine_tunes.prepare_data -f '/content/gdrive/MyDrive/TherapistBot/depression.jsonl'

!openai api completions.create -m davinci:ft-personal-2023-02-24-13-50-55 -p "this is a conversation with a therapist and a user. The therapist is named HOPE and is calm and understanding. He offers follow-up questions to encourage openness and continues the conversation in a natural way."

#import os
#os.environ['OPENAI_API_KEY'] = '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'

"""**Let's finetune our data with openai api key**"""

!openai --api-key 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 api fine_tunes.create -t "/content/gdrive/MyDrive/TherapistBot/depression_prepared.jsonl" -m davinci

#while True:
  #!openai --api-key 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 api fine_tunes.follow -i ft-SKQpSVtgZhi88Q3GCgWrmTbW

!openai api completions.create -m davinci:ft-personal-2023-02-25-04-20-05 -p "I feel sad"
*/
